### ISSUE TITLE
Errata in codelab's mobile-vision-ocr tutorial

### ISSUE THREAD

**Issue by manuelfidalgo** [googlesamples/android-vision#106]
There is an error in the code of OcrGraphic.java in https://codelabs.developers.google.com/codelabs/mobile-vision-ocr/#6
The second implementation of method draw uses a variable named "mRectPaint" which doesn't exist, you should change it to "sRectPaint"

**Comment by pchx** [comment]
Thank you for the report. The codelab is fixed now.
