### ISSUE TITLE
ocr-reader - Build error - Cannot assign mText

### ISSUE THREAD

**Issue by davidtcdeveloper** [googlesamples/android-vision#108]
The project `ocr-reader` has this compilation error:

```Error:(81, 9) error: cannot assign a value to final variable mText```

The method `updateItem` from class `OcrGraphic` tries to set the value from the final field `mText`.
This method is not referenced anywere and i think it can be deleted.
By deleting it the project can be built and works fine.

I can send a PR with this deletion if you need it.

**Comment by theoreticalb** [comment]
Pushed a fix that removes the `updateItem` method.  Thank you, David!
