### ISSUE TITLE
Can't add JPEG as supported format for Frame

### ISSUE THREAD

**Issue by AmlanDwivedy** [googlesamples/android-vision#109]
I am trying to read image stored in sdcard. The image is jpeg. When I am creating frame its crashing

            TextRecognizer textRecognizer = new TextRecognizer.Builder(MyScanActivity.this).build();
            textRecognizer.setProcessor(new OcrDetectorProcessor(mGraphicOverlay));

            String filePath = data.getStringExtra(....);
            Bitmap bitmap = BitmapFactory.decodeFile(filePath);
            imageView.setImageBitmap(bitmap);

            int bytes = 0;
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.HONEYCOMB_MR1) {
                bytes = bitmap.getByteCount();

                //or we can calculate bytes this way. Use a different value than 4 if you don't use 32bit images.
                //int bytes = b.getWidth()*b.getHeight()*4;

                ByteBuffer buffer = ByteBuffer.allocate(bytes); //Create a new buffer
                bitmap.copyPixelsToBuffer(buffer); //Move the byte data to the buffer

                Frame outputFrame = new Frame.Builder()
                        .setImageData(buffer, bitmap.getWidth(),
                                bitmap.getHeight(), ImageFormat.JPEG)
                        .setId(new Random().nextInt())
                        .setTimestampMillis(new Date().getTime())
                        .setRotation(0)
                        .build();
                textRecognizer.receiveFrame(outputFrame);
}

 Caused by: java.lang.IllegalArgumentException: Unsupported image format: 256

**Comment by pm0733464** [comment]
When creating outputFrame, use the builder's "setBitmap" method rather than "setImageData", like this:

```
Frame outputFrame = new Frame.Builder()
                    .setBitmap(bitmap)
                    .setId(new Random().nextInt())
                    .setTimestampMillis(new Date().getTime())
                    .setRotation(0)
                    .build();
```

[setBitmap](https://developers.google.com/android/reference/com/google/android/gms/vision/Frame.Builder.html#setBitmap(android.graphics.Bitmap))

**Comment by AmlanDwivedy** [comment]
Thank you buddy. It worked
