### ISSUE TITLE
PDF417 and Driver License Scan not detected

### ISSUE THREAD

**Issue by djkrut** [googlesamples/android-vision#11]
I have tried this sample after implementing other camera solutions (cwac-cam2, native camera).  I have not successfully been able to decode a pdf417 or Driver License bar code.  I have no problem with 1D or QR codes.

**Comment by pchx** [comment]
There is a known issue with driver's licenses from certain states (for example, Illinois) not conforming to the PDF417 spec. We have developed a fix and hope to release it soon.

**Comment by hanzo3** [comment]
Awesome, great to hear!  Thank you.

**Comment by jianleon** [comment]
How can I only recognize one specific barcode type?

**Comment by hanzo3** [comment]
You can capture all barcodes and process only the type you need.
You can get the specific type by using the following code:detector = new BarcodeDetector.Builder(getActivity().getApplicationContext())
        .setBarcodeFormats(Barcode.DRIVER_LICENSE | Barcode.PDF417)
        .build();
You can also check the format type and if it equals what you want to evaluate then continue processing or capture the barcode.
Hope this helps or answers your question.  If not, let me know. 


     On Tuesday, August 25, 2015 9:47 AM, jianleon <notifications@github.com> wrote:
   

 How can I only recognize one specific barcode type?—

**Comment by pchx** [comment]
hanzo3: We're getting off-topic, but this isn't entirely correct:

detector = new BarcodeDetector.Builder(getActivity().getApplicationContext())
        .setBarcodeFormats(Barcode.DRIVER_LICENSE | Barcode.PDF417)
        .build();

setBarcodeFormats() only works with the barcode format constants (e.g. Barcode.PDF417). DRIVER_LICENSE is a value format type that is only used in the detector output via Barcode.valueFormat.

**Comment by hanzo3** [comment]
Oh yeah, good catch.  I was going to test that as it seemed odd since DL is PDF417 but never got the Drivers License to work in my state.  I did get it to work from an online example from a different state and should have read the doc instead of assuming with code assist.  Thanks!

**Comment by pchx** [comment]
The PDF417 decoding fix was released with Play Services 8.3:

  https://developers.google.com/vision/release-notes

For drivers license parser improvements, please refer to issue #77.
