### ISSUE TITLE
Wrong face detection.

### ISSUE THREAD

**Issue by vardan007** [googlesamples/android-vision#112]
Try face detection for this image:

![thumb_img_0042_1024](https://cloud.githubusercontent.com/assets/20239063/17108294/ed329a76-52a3-11e6-9f7e-95ca86f43d7b.jpg)

With this configuration:
   FaceDetector detector = new FaceDetector.Builder(getContainerActivity())
                .setTrackingEnabled(false)
                .setMode(FaceDetector.ACCURATE_MODE)
                .build();

See face detection result, top is -321.

I am asking is this a bug? or this is an approximate value of the possible top value?

**Comment by pm0733464** [comment]
See my answer here:

[face-detection-api-coordinates](http://stackoverflow.com/questions/38449771/face-detection-api-coordinates/38464960#38464960)

> The bounding box estimates the dimensions of the head, even though it may not be entirely visible within the photo. The coordinates may be negative if the face is cropped by the top or left of the image (e.g., the top of the head is cropped off the top of the picture, resulting in a y coordinate above 0).

**Comment by vardan007** [comment]
@pm0733464  thanks :)
Closing issue.
