### ISSUE TITLE
Android vision not working 3th August for 10 minutes on all devices

### ISSUE THREAD

**Issue by knyttl** [googlesamples/android-vision#118]
During 3rd August, it happened to us, that all our devices refused to scan codes for about 10 minutes. We tried to restart the app, the devices, with no effect. The devices were online and we wonder, whether there is some communication between the devices and google android vision servers. I wonder if it is similar case like when the vision api was disabled.

**Comment by pchx** [comment]
There's no further communication after the initial library download is complete. It's likely that this was just a coincidence.
