### ISSUE TITLE
VisionApi, apply regex for Business card reader and save result.

### ISSUE THREAD

**Issue by Nbi007** [googlesamples/android-vision#122]
I am trying to build a Business Card Reader, so far i am able to recognize text but i just can't seem to apply regex and display the achieved results in an activity. Has any one experienced or working on this .

**Comment by pchx** [comment]
GitHub issues aren't the best place to ask questions like this. I would suggest asking on StackOverflow (making sure to include more detail on what you've tried and what isn't working):

http://stackoverflow.com/questions/tagged/android-vision
