### ISSUE TITLE
Could not find any version that matches com.google.android.gms:play-services:7.8.+

### ISSUE THREAD

**Issue by jianleon** [googlesamples/android-vision#13]
When I try to build the project. I got this message

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services:7.8.+.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/android/gms/play-services/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services/
         file:/home/user/Sdk/extras/android/m2repository/com/google/android/gms/play-services/maven-metadata.xml
         file:/home/user/Sdk/extras/android/m2repository/com/google/android/gms/play-services/
         file:/home/user/Sdk/extras/google/m2repository/com/google/android/gms/play-services/maven-metadata.xml
     Required by:
         photo-demo:app:unspecified

How can I download the library?

**Comment by Gericop** [comment]
Have you updated Google Play services through the Android SDK Manager? The latest revision is 26.

**Comment by jianleon** [comment]
I just did and didn't work.
Do I need any other update or package to make it work?

**Comment by jianleon** [comment]
I updated all the extra files and if worked.
Thank you.
