### ISSUE TITLE
Very bad performance for scanning QRCode at short distance on Nexus 5X

### ISSUE THREAD

**Issue by ggirard07** [googlesamples/android-vision#130]
Just giving a try to an existing app based on Google mobile vision API to scan QRCodes.
I am now getting really bad performance for scanning at short distance, camera is placed between 5cm to 12cm from the code. Longer distances seem fine (greater than 15cm).
Sometimes the barcode is detected, most of the time it is not. When it is detected, tracker is receiving only a few position updates (2 to 10 updates) prior the barcode is declared missing then done (even if the phone doesn't move in the meantime).
Previously, I was able to scan with my Nexus 5X from those distances without any issue.
I did the same tests on a Samsung Galaxy SIII (i9300) running Cyanogenmod 11 (Android 4.4.4), but this one is not impacted by the issue and barcode detection is working totally fine.

I have seen the following logs in the monitor I have never noticed previously:

```
09-15 12:19:00.642: D/ChimeraCfgMgr(14130): Reading stored module config
09-15 12:19:00.818: E/dex2oat(14163): Failed to create oat file: /data/dalvik-cache/arm/data@data@com.google.android.gms@app_chimera@m@00000008@DynamiteModulesB_GmsCore_prodmnc_alldpi_release.apk@classes.dex: Permission denied
09-15 12:19:00.819: I/dex2oat(14163): dex2oat took 1.231ms (threads: 2) 
09-15 12:19:00.821: W/art(14130): Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=smp,div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m -j2 --instruction-set-variant=cortex-a7 --instruction-set-features=default --dex-file=/data/data/com.google.android.gms/app_chimera/m/00000008/DynamiteModulesB_GmsCore_prodmnc_alldpi_release.apk --oat-file=/data/dalvik-cache/arm/data@data@com.google.android.gms@app_chimera@m@00000008@DynamiteModulesB_GmsCore_prodmnc_alldpi_release.apk@classes.dex) because non-0 exit status
09-15 12:19:00.918: W/System(14130): ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi-v7a
09-15 12:19:00.919: W/System(14130): ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi
09-15 12:19:00.920: D/ChimeraFileApk(14130): Primary ABI of requesting process is armeabi-v7a
09-15 12:19:00.921: D/ChimeraFileApk(14130): Classloading successful, but code may not be optimized. It will either run in fallback (interpreted mode) or the odex has been found and isDexOptNeeded is misreporting a failure.
```

QRCode is printed with the following configuration
- Version 3 (29x29 modules)
- Correction level L
- Alphanumeric with UTF-8 encoding
- Printed at 203DPI (15mils)
  The resulting QRCode is 14.1mm

Nexus 5X info
- Google Play Services 9.4.52
- Vision module version 6
- Vision.dynamite module version 6

i9300 info
- Google play Services 9.4.52

**Comment by pchx** [comment]
So you were previously able to scan QR codes using the Vision API on both the Nexus 5X and the Galaxy?

The QR reader implementation has not changed since the initial release, so if you've noticed any change in performance it may be due to the hardware or some other part of your application. For example, does your app enable autofocus?
