### ISSUE TITLE
Problem detecting barcodes 'framed' in black backgrounds 

### ISSUE THREAD

**Issue by richehmer** [googlesamples/android-vision#131]
The library has trouble detecting barcodes 'framed' in a dark color. For example, a barcode printed on a white sticker stuck on a dark surface. If the ends of the barcode are close to the edge of the sticker, the library won't detect unless at least one side of the dark framed portion is cropped out of the input image. (play services version code 8115000)

My guess is that barcode standards allow for a certain amount of whitespace on either side of the barcode that the library doesn't seem to account for. The whitespace is important because it allows _non-inverted_ barcodes to be printed on dark surfaces (see attached BMW, GM, and Toyota VIN barcodes).

Open the three example images below to full-screen, center the barcode in the app, and slowly pan the camera left until the right edge of the preview screen reaches the white 'padding' area of the barcode, then the barcode will be recognized.

![vw-vin](https://cloud.githubusercontent.com/assets/1414630/18686346/9c48768a-7f49-11e6-88a4-b9579352fd2b.jpg)

![bmw-vin](https://cloud.githubusercontent.com/assets/1414630/18686361/a43eda82-7f49-11e6-8cf9-9eb23e78e157.jpg)

![gm-vin](https://cloud.githubusercontent.com/assets/1414630/18686364/a802363c-7f49-11e6-9749-0636ce680730.jpg)

Ignore the figure below because you can't reproduce the bug with it, and I haven't gotten it to scan at all. I just wanted to include it to show another major manufacturer uses barcodes on dark backgrounds.
![toyota-vin](https://cloud.githubusercontent.com/assets/1414630/18686450/f7e8beaa-7f49-11e6-9935-364ca981dc64.jpg)

**Comment by pchx** [comment]
Thanks for the report.

The code39 reader does indeed incorrectly require too much quiet space around barcodes. We expect to fix this in a future release of the Barcode API, though I don't have a specific date to announce.

**Comment by pchx** [comment]
The latest version of our Barcode API (part of [Google Play Services 10.0](https://developers.google.com/vision/release-notes#google_play_services_100)) reduces the code39 quiet zone requirement.
