### ISSUE TITLE
GMS fails to download vision libraries

### ISSUE THREAD

**Issue by renclav** [googlesamples/android-vision#14]
Hi,

First off, thank you for your continued fast paced updates, never a dull moment in the Android world.

Attempting to run the multitracker example on my device fails as the GMS library download never completes with 'isOperational' always returning false. This occurs on both wireless and mobile networks.

An excerpt from logcat:
```
08-24 17:41:15.377    9950-9950/? I/art﹕ Late-enabling -Xcheck:jni
08-24 17:41:15.377    9950-9950/? I/art﹕ VMHOOK: rlim_cur : 0 pid:9950
08-24 17:41:15.497    9950-9950/com.google.android.gms.samples.vision.face.multitracker W/ResourcesManager﹕ Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
08-24 17:41:15.497    9950-9950/com.google.android.gms.samples.vision.face.multitracker W/ResourcesManager﹕ Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
08-24 17:41:15.537    9950-9950/com.google.android.gms.samples.vision.face.multitracker I/Vision﹕ Supported ABIS: [armeabi-v7a, armeabi]
08-24 17:41:15.537    9950-9950/com.google.android.gms.samples.vision.face.multitracker D/Vision﹕ Library not found: /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
08-24 17:41:15.537    9950-9950/com.google.android.gms.samples.vision.face.multitracker I/Vision﹕ Requesting barcode detector download.
08-24 17:41:15.547    9950-9950/com.google.android.gms.samples.vision.face.multitracker W/MultiTracker﹕ Detector dependencies are not yet available.
08-24 17:41:15.557    9950-9950/com.google.android.gms.samples.vision.face.multitracker D/Atlas﹕ Validating map...
08-24 17:41:15.597    9950-9987/com.google.android.gms.samples.vision.face.multitracker I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030_msm8974_refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030__release_AU ()
    OpenGL ES Shader Compiler Version: E031.25.03.00
    Build Date: 12/11/14 Thu
    Local Branch:
    Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030
    Local Patches: NONE
    Reconstruct Branch: NOTHING
08-24 17:41:16.727    9950-9950/com.google.android.gms.samples.vision.face.multitracker I/Camera﹕ hasFeature com.htc.vtetrue
08-24 17:41:16.767    9950-9950/com.google.android.gms.samples.vision.face.multitracker I/Choreographer﹕ Skipped 71 frames!  The application may be doing too much work on its main thread.
08-24 17:41:16.807    9950-9950/com.google.android.gms.samples.vision.face.multitracker D/Camera﹕ HTC_CALLBACK: callbackType=12 arg1=0 arg2=0 mHtcCallback=null
08-24 17:41:16.817   9950-10193/com.google.android.gms.samples.vision.face.multitracker W/ResourcesManager﹕ Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
08-24 17:41:16.817   9950-10193/com.google.android.gms.samples.vision.face.multitracker W/ResourcesManager﹕ Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
08-24 17:41:20.767   9950-10193/com.google.android.gms.samples.vision.face.multitracker I/art﹕ Explicit concurrent mark sweep GC freed 20510(2MB) AllocSpace objects, 54(863KB) LOS objects, 40% free, 10MB/18MB, paused 571us total 20.664ms
```

With the last three issues recurring.

Device Details:
HTC ONE_M8
Android Version 5.0.1

Thank You,
Dylan

**Comment by pm0733464** [comment]
The first thing to try is to free up storage space.  How much free storage space do you have on the device?

Note that the download mechanism is a bit conservative, so as not to leave you in a state where you don't have much storage space left.  If there is less than, say, 10% storage space remaining, it may not download those libraries (however, it doesn't actually use this much space).

**Comment by renclav** [comment]
Hi @pm0733464 ,

Creating space did solve the issue. With that in mind, could you please let me know if there are any plans to either

* Add callbacks to the library loading lifecycle
* Provide a mechanism to ship with the library bundle included with, perhaps as an added bonus, a means to update to the latest version via GMS

Thank You,
Dylan

**Comment by pm0733464** [comment]
Discussions are underway w.r.t. potential improvements to the downloading mechanism.  We'll consider your suggestion on callbacks.

Bundling the library with the APK was something that we implemented internally, but chose not to include due to its drawbacks: (1) it would require developers to package/distribute multiple versions of their app for different hardware architectures, (2) every app using the functionality would have included the same library redundantly, using up space unnecessarily on the user's device, (3) it's not possible to update a bundled library via GMS.

**Comment by renclav** [comment]
Thank you very much @pm0733464 . I will be monitoring this lib closely and am looking forward to replacing our 3rd party versions. Unfortunately, without any lifecycle callbacks and/or resolution strategies (such as GCM), this has yet to become a viable production solution for our ecommerce apps.

**Comment by tajchert** [comment]
I have same problem - Nexus 4 with 5.1.1 CyanogenMod 12.1, and GMS 8.3.0, over 1,1 GB free space, reliable Internet connection and still will always get "false" in "isOperational()".

The API to check if is working is poor (very less information) and as well callbacks would be nice.
