### ISSUE TITLE
Is there any possible way to install native library for QR-code scanner without internet access.

### ISSUE THREAD

**Issue by darkmoment0088** [googlesamples/android-vision#142]
Im building an application with a barcode scanner, i have tried multiple QR-code scanner so far, this is a good library, but the downside is the need of downloading native library as my client might be installing the application on a location where internet access is not possible.

any suggestion or help would be nice.

**Comment by pchx** [comment]
No, the native code cannot be installed without Internet access. However, you can declare a dependency on the Vision API by editing your project's AndroidManifest.xml, as described here:

https://developers.google.com/android/reference/com/google/android/gms/vision/package-summary#manifest_dependency

By doing this, the native dependencies will be downloaded shortly after your application is installed (when the user likely has network access).
