### ISSUE TITLE
Barcode not detecting from Code 39 Image Bitmap using Frame with BarcodeDetector

### ISSUE THREAD

**Issue by dibakarece** [googlesamples/android-vision#147]
I am trying to detecting bar code from Image bitmap (Format - code 93).But it cant.It will only detecting code form QR Image bitmap.

Bitmap myBitmap = BitmapFactory.decodeResource(
                    getApplicationContext().getResources(),
                    R.drawable.barcode_39);

Frame frame = new Frame.Builder().setBitmap(myBitmap).build();
SparseArray<Barcode> barCodes = barcodeDetector.detect(frame);

if (barCodes != null && barCodes.size() >= 1) {
     Barcode thisCode = barCodes.valueAt(0);
     String code = thisCode.rawValue;
     LogWriter.info(TAG + " Detect Code :  ", code);
}
![barcode_1d](https://cloud.githubusercontent.com/assets/10453203/19761637/56a32268-9bfc-11e6-8fa6-7ceb5a6672bd.png)

**Comment by pchx** [comment]
You omitted the code that constructs barcodeDetector, so I'll have to ask the obvious question: what formats are you building the detector with? Either don't call BarcodeDetector.Builder.setBarcodeFormats at all, or make sure you pass in a bitmask that includes Barcode.CODE_39 (or 93; you mention both).

The other possible issue is that your image doesn't include the required quiet zone (a few extra white pixels to the left and right) around the barcode. I've verified that it decodes fine against a white background, but the decoded Bitmap contains no such padding.

**Comment by dibakarece** [comment]
Thanks @pchx for your kind reply back.Finally I got the issue.You are right, actual problem with the barcode image, I have test with different barcode image with some extra white pixels to the left and right and it working well.Thanks man for your effort.

I assigned my BarcodeDetector as follow...
 detector =new BarcodeDetector.Builder(getApplicationContext())
                        .setBarcodeFormats(Barcode.ALL_FORMATS)
                        .build();
