### ISSUE TITLE
Will CameraSource for hardware.Camera2 be possible?

### ISSUE THREAD

**Issue by EzequielAdrianM** [googlesamples/android-vision#157]
Hi, after struggling five days trying to create a new CameraSource class but with Android Camera 2, I found something that I truly can't understand. This line of code is making things impossible:

`camera.addCallbackBuffer(mPendingFrameData.array());`

Since the addCallbackBuffer does not exist in Camera2... any solution?

Why I am making this? Because I want all the power of Google Vision Face Detector API on the Camera 2 Preview. Instead of using the native Face API included with camera2 that is very basic (does not include Euler Z nor Nose Position). Thanks!

**Comment by victor-lund** [comment]
Any update here? An implementation of camera2 in the CameraSource socket would be a great feature! 

Coolest of all would of course be if CameraSource could determine if your device has API level < 21 (and in that case use legacy camera software) - or API >= 21 and then use camera2!

**Comment by pm0733464** [comment]
I am not aware of any plans to develop an official camera2 version of CameraSource.  But it would be good if the developer community would develop one, which is possible since it would not require any changes to the existing public vision API.

**Comment by EzequielAdrianM** [comment]
[Camera2Vision](https://github.com/EzequielAdrianM/Camera2Vision)
