### ISSUE TITLE
Get The Face bitmap from face detector

### ISSUE THREAD

**Issue by tperl** [googlesamples/android-vision#167]
Hi,

In the Face class documentation it gives API for getting all sorts of landmarks of the face, i.e eyes, nose, rotation, location in the frame.

If I want to use the whole face cropped out of the frame is there a way to do so from the API?

I am struggling in doing this from the frame itself, because the detector is connected to the camera preview without any access from the user to the preview frames, it also skips frames for performance.

How can I for example in FaceGraphic draw method - before I draw a circle around the face, get the entire face from the frame? and send it somewhere else?

is this possible?

**Comment by pm0733464** [comment]
You can access the preview frame image as described here:

http://stackoverflow.com/questions/32299947/mobile-vision-api-concatenate-new-detector-object-to-continue-frame-processing/32314136#32314136

**Comment by tperl** [comment]
The link helps me get the "frame" but not its bitmap, I want to get the real frame, like I would from a matrix in openCV implementation, a databuffer would also suffice.

**Comment by rahulkulhalli** [comment]
Yes, it's pretty simple to do so.

Assuming you've initialized your frame and loaded the full image bitmap into it, this is what I'd normally do:

SparseArray<Face> detectedFaces = detector.detect(frame);
for(int i=0;i<detectedFaces.size();i++){          //can't use for-each loops for SparseArrays
    Face face = detectedFaces.valueAt(i);
    //get it's coordinates
    Bitmap faceBitmap = Bitmap.createBitmap(bitmap, (int) face.getPosition().x, (int) face.getPosition().y, (int) face.getWidth(), (int) face.getHeight());

    //Do whatever you want with this cropped Bitmap
}

**Comment by jagdeesh94** [comment]
Could you please tell about the bitmap in the first argument of createBitmap.Where did it come from?Is that an empty bitmap?

**Comment by liuyl** [comment]
frame.getBitmap() returns the bitmap.

**Comment by sumitatflo** [comment]
@jagdeesh94 Were you able to find a working solution to this?

**Comment by bako-ak** [comment]
sorry for my English :), you can see an example using "takePicture", after the capture of the image are cropped the face and passed mainFragment.
https://github.com/bako-ak/face-detection

**Comment by jagdeesh94** [comment]
@bako-ak ,thanks for your input dude.Could you tell me where is the "takePicture" method that you are referring?.

**Comment by bako-ak** [comment]
@jagdeesh94  in a branch "develop" https://github.com/bako-ak/face-detection/blob/develop/app/src/main/java/kz/bako/facedetection/face/FaceFragment.kt  
the line 39 is called when you click the button, after pressing the method calls "onPictureTaken", then get the face and pass back as a result.

**Comment by manuja96** [comment]
@rahul its great and working but i want multiple faces in multiple imageview,any solution please?send me on manujagourav@gmail.com

**Comment by tush23** [comment]
Can anyone pleaae help me regarding same issue??
