### ISSUE TITLE
pause barcode detection on successful detection callback

### ISSUE THREAD

**Issue by monajafi** [googlesamples/android-vision#173]
I want to show the data upon successful detected barcode on dialogfragment without leaving BarcodeCaptureActivity and after pressing ok button on dialog rescan the barcode  like the scandit or zbar. I tried mpreview.stop() and barcodeDetector.release() on success calback but they caused exception.

**Comment by monajafi** [comment]
I solved the problem by calling mPreview.stop() using Handler on UI thread but still I need a faster solution like pausing detector and resuming how should I do this

**Comment by pchx** [comment]
Try consulting [StackOverflow](http://stackoverflow.com/tags/android/info) for questions like these. The issue tracker is for reporting bugs.
