### ISSUE TITLE
autofocus is not working after zooming the camera preview

### ISSUE THREAD

**Issue by monajafi** [googlesamples/android-vision#176]
Camera does not focus well after zooming the camera preview. I compared the effect of zooming with the Scandit api which is functioning much better in long distances compared to vision api. because it is focusing better in zoomed state. Also their app has a higher resolution and sharper camera view
whether zoomed or not. because of theses differences scandit detection range is more than vision api

**Comment by pchx** [comment]
This has nothing to do with the Vision API itself, which does not control autofocus behavior. If you believe higher resolution would help, try increasing the preview frame size when initializing CameraSource:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/BarcodeCaptureActivity.java#L205

**Comment by monajafi** [comment]
I think if focus triggers more than what Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE
provides the detection speed will be more. I realised the more focus frequency in a Scandit api which is superior than Vision Api in regard of speed and distanse of detectin.
