### ISSUE TITLE
barcode application size is different on S5 with api 23 and s4 mini with api 17

### ISSUE THREAD

**Issue by monajafi** [googlesamples/android-vision#178]
Installed barcode reader sample app size for S5 with Api 23 is 17Meg but in S4 mini with Api 17 is 5 Meg
why there is huge difference in application size in these two devices. Is this related for Native Libraries?
I tried midified version of sample without tracker and application size was same in two devices

**Comment by pchx** [comment]
No. The native libraries are downloaded into a common location (managed by Play Services) on your device at runtime, so they have no impact on your application's APK size.
