### ISSUE TITLE
How to track progress of dependency download?

### ISSUE THREAD

**Issue by arslan70** [googlesamples/android-vision#204]
If the device is running on a slow connection, it takes forever to load the libraries required by android vision. Is there a way to show a progress bar. 
I believe there should be a graceful mechanism instead of showing a "please wait" message forever.

**Comment by bloomer20102011** [comment]
have you found a solution to this?

**Comment by arslan70** [comment]
Detect if the required version is installed otherwise open play store with link to play services. 

The idea is to de-couple the download from your app. This is a good approach because the user can trust and see the progress on play store.

User will upgrade play services and return to your app. You can use the onResume method of the activity to check if the version is now available.
