### ISSUE TITLE
Reading Micro QR Code

### ISSUE THREAD

**Issue by beyerleinf** [googlesamples/android-vision#229]
Hello,

is it possible to read micro QR Code with Android Vision? (http://www.qrcode.com/en/codes/microqr.html)
I didn't have any luck so far...

Thanks in advance and best regards

**Comment by pchx** [comment]
No, the Barcode API unfortunately does not support Micro QR codes.

**Comment by gigot13610** [comment]
Hi,
You knows any app able to read Micro QR Code?
regards,
Gigot

**Comment by lessthanoptimal** [comment]
Not part of Android Vision but I've written a Micro QR Code reader that runs on Android. https://boofcv.org/index.php?title=Example_Detect_Micro_QR_Code
