### ISSUE TITLE
barcodedetector.detect returns empty array from a QR-code image

### ISSUE THREAD

**Issue by ashkoret** [googlesamples/android-vision#236]
I have an image of a QR-code, and passing this image to the barcodedetector and it returns an empty array. I even cropped the QR-code, there is nothing except it on the image, still doesn't work.

                        BarcodeDetector barcodeDetector =
                        new BarcodeDetector.Builder(this)
                                .setBarcodeFormats(Barcode.QR_CODE)
                                .build();
                if (barcodeDetector.isOperational())
                {
                    Frame myFrame = new Frame.Builder()
                        .setBitmap(myQRCode)
                        .build();
                    SparseArray<Barcode> barcodes = barcodeDetector.detect(myFrame);
                    
                    // Check if at least one barcode was detected
                    if (barcodes.size() != 0) {
                       QRCode = barcodes.valueAt(0).toString();
                    }
                    else
                    {
                        QRCode = getString(R.string.barcode_empty);
                    }
                }
                else
                {
                    QRCode = getString(R.string.barcode_service_down);
                }
                barcodeDetector.release();
            }

Where is the error? It's pretty much the sample code from the google tutorial.
The Frame is not empty, I can see the image. I'm trying Sony XperiaZ1 with
play-services:10.2.4.

**Comment by ajhool** [comment]
Have you experimented with other barcodes to confirm that the code does not work on any? There was a recent issue involving a certain barcode standard that was failing, although I think that issue was resolved.

**Comment by pchx** [comment]
Would it be possible to see an example image that demonstrates the problem?

**Comment by ashkoret** [comment]
I've figured it out, the image resolution was too big, rescaling the image helped.
