### ISSUE TITLE
setImageData not working with YuvImage object data?

### ISSUE THREAD

**Issue by Shivang44** [googlesamples/android-vision#243]
If I do this:
```

Frame frame = new Frame.Builder().setBitmap(bitmap).build();
SparseArray<Face> faces = detector.detect(frame);
```

Everything is good -- my face is detected and I can get the smiling probability and such. 

For some reason it does not work with [YuvImage ](https://developer.android.com/reference/android/graphics/YuvImage.html)like this:

`Frame frame = new Frame.Builder().setImageData(ByteBuffer.wrap(yuvImage.getYuvData()), yuvImage.getWidth(), yuvImage.getHeight(), yuvImage.getYuvFormat()).build();
`
It doesn't throw any errors, but it doesn't detect my face.

I believe yuvImage is created properly because I used this yuvImage to convert to a bitmap and the detector was able to detect my face in the bitmap. But when I use the YuvImage.getYuvData() directly it does not work. Any ideas?

Thanks

**Comment by Shivang44** [comment]
Turns out I just had to do a .setRotation(Frame.ROTATION_270) because the frame Twilio was sending me was rotated. Sorry about that.

**Comment by VerifyMan** [comment]
@Shivang44 could you help me here:https://stackoverflow.com/questions/52145789/android-studio-face-detection-failed-e-camerasource-exception-thrown-from-rec
I'm trying to do the same but not working
