### ISSUE TITLE
tgkill crash reports in play store console 

### ISSUE THREAD

**Issue by hm122** [googlesamples/android-vision#245]
Hi!

I am using android vision to read a qr code. Everything works fine for many devices I have tested the code, but still I am getting crash reports on the play store console regarding the vision api.

`
backtrace:
  native: pc 00000000000444e4  /system/lib/libc.so (tgkill+12)
  native: pc 00000000000420f1  /system/lib/libc.so (pthread_kill+32)
  native: pc 000000000001bb6f  /system/lib/libc.so (raise+10)
  native: pc 0000000000018d21  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 00000000000168e0  /system/lib/libc.so (abort+4)
  native: pc 0000000000020d65  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 00000000000214c1  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 000000000002136f  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 00000000000210e9  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 0000000000020117  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 0000000000020133  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 000000000000a36b  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 0000000000003333  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 000000000000442d  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 0000000000001e63  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so
  native: pc 0000000000002a91  /data/data/com.google.android.gms/files/com.google.android.gms.vision/barcode/libs/armeabi-v7a/libbarhopper.so (Java_com_google_android_gms_vision_barcode_internal_NativeBarcodeDetector_recognizeNative+40)
  native: pc 00000000004dc53f  /data/data/com.google.android.gms/app_chimera/m/0000000d/oat/arm/DynamiteModulesA_GmsCore_prodmnc_xhdpi_release.odex
`

How can I fix this or handle the error?

Thanks a lot!

**Comment by pchx** [comment]
Thanks for the report. We believe we have identified the root cause and will push a fix in a future release.

You can work around the crash if you don't need PDF417 decoding in your application; simply disable it by calling setBarcodeFormats() when building the BarcodeDetector. Unfortunately, there is no easy fix if you need to read the PDF417 symbology.

**Comment by hm122** [comment]
Awesome, thanks for your answer! Since I only need to scan QR-codes, that workaround is perfectly fine.
