### ISSUE TITLE
Multiple bar code scanning taking wrong barcode on tap

### ISSUE THREAD

**Issue by pnjolapara** [googlesamples/android-vision#248]
I had implemented google barcode scanning from _https://github.com/googlesamples/android-vision/tree/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereade_r

When there are multiple bar codes are displayed on screen and user tap on the blank screen where the bar code is not scane, its randomly choosing any detected barcode and close the screen.

**Comment by pchx** [comment]
If there isn't an exact hit, it picks the barcode whose center is closest to the tap location:
https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/BarcodeCaptureActivity.java#L342
