### ISSUE TITLE
Barcode -Code_39-  recognition extra number

### ISSUE THREAD

**Issue by lucasjj85** [googlesamples/android-vision#25]
Hello,
i get some extra numbers when detecting Barcode Code-39 type. I use the following code to detect Code-39 and Code128 (i also use the workaround you suggested for the camera focus):

Code from MultiTrackerActivity.java

private void createCameraSource() {
        Context context = getApplicationContext();        
        BarcodeDetector barcodeDetector = new BarcodeDetector.Builder(context)
        .setBarcodeFormats(Barcode.CODE_39 | Barcode.CODE_128 )
        .build();
        
        BarcodeTrackerFactory barcodeFactory = new BarcodeTrackerFactory(mGraphicOverlay, new GraphicTracker.Callback() {
            @Override
            public void onFound(Barcode barcodeValue) {
               //my callback function
            	Log.d(TAG, "Barcode in Multitracker = " + barcodeValue.displayValue);
            	Intent output = new Intent();
            	output.putExtra("barcodeValue", barcodeValue.displayValue);
            	output.putExtra("barcodeFormat", barcodeValue.valueFormat);
            	setResult(RESULT_OK, output);
            	finish();                
            }
        });
        barcodeDetector.setProcessor(new MultiProcessor.Builder<>(barcodeFactory).build());

        if (!barcodeDetector.isOperational()) {
            // Note: The first time that an app using the barcode or face API is installed on a
            // device, GMS will download a native libraries to the device in order to do detection.
            // Usually this completes before the app is run for the first time.  But if that
            // download has not yet completed, then the above call will not detect any barcodes
            // and/or faces.
            //
            // isOperational() can be used to check if the required native libraries are currently
            // available.  The detectors will automatically become operational once the library
            // downloads complete on device.
            Log.w(TAG, "Detector dependencies are not yet available.");
        }

        // Creates and starts the camera.  Note that this uses a higher resolution in comparison
        // to other detection examples to enable the barcode detector to detect small barcodes
        // at long distances.
        mCameraSource = new CameraSource.Builder(getApplicationContext(), barcodeDetector)
                .setFacing(CameraSource.CAMERA_FACING_BACK)
                .setRequestedPreviewSize(1600, 1024)
                .setRequestedFps(25.0f)
                .build();
    }

In most cases the results are really fine, but sometimes the detection results are not corresponding to the real code. The example below shows an extra "I" at the beginning. I tried with Zxing library with same image and same environment and the result is fine, without "I" at the beginning.

My app with mobile vision library (wrong- "I" at beginning): 
![mobilevision](https://cloud.githubusercontent.com/assets/7116439/9884554/a3570424-5be0-11e5-8246-dc61af59b91c.png)

Barcodescanner with Zxing app (correct):
![barcodescannerz-xing](https://cloud.githubusercontent.com/assets/7116439/9884565/b28b92d4-5be0-11e5-8216-ab47e427fad1.png)

Thanks for any suggestions.

**Comment by lucasjj85** [comment]
I solved this issue normalizing the results.  In my case CODE 39 is used to obtain VIN (veichle identification number) so I cleaned the results using VIN template. 

Thank you

**Comment by phocea13** [comment]
Hi man - so I'm trying to put something together to scan VIN barcodes as well, and I'm having some challenges with the sample app not consistently picking up code 39 barcodes. It is very consistent and fast with Qr codes and other formats, but it required more work and fiddling around on code 39s. Wonder if you had more luck, and if you made significant changes to the sample app to make it work better for VIN barcodes.

**Comment by pchx** [comment]
ZXing is parsing the VIN (note the "Tipo VIN" text in the screenshot above) and removing the leading "I" character:

https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/VINResultParser.java

If you look at the scan history in the Barcode Scanner application, you'll notice the barcode's raw text actually does begin with an "I". If you're noticing an apparent disagreement between our API's results and ZXing, this is likely the reason why.

**Comment by phocea13** [comment]
Thanks for the quick response. I wasn't really comparing zxing and google vision. My focus was on trying to make the solution work using Google Vision and its barcode scanner sample app. Just had some challenges around picking up some VIN barcodes and I was wondering if someone had more luck before with the same API.

**Comment by pchx** [comment]
If you're having trouble with Code 39 that isn't explained by the above, please file a new issue with details on what extra fiddling was needed and any example images, etc. you might have.

Note that some VIN barcodes don't seem to include a check character, which makes it difficult to eliminate false positives.

**Comment by lucasjj85** [comment]
Hi phocea13 ,
as pchx has pointed out in the previous post, i've used the same tecnique used by ZXing library, "cleaning " the result of a scan (removing some characters not present in the VIN format like I-Q-O). 
This is working good enough with 95% of accuracy, except some VIN without check digit.
I used the same link pchx posted before, as a guide to develop my VINParser class, https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/VINResultParser.java .

If you need more help i'm here :-)
