### ISSUE TITLE
isOperational return false (libbarhopper.so library load status: false)

### ISSUE THREAD

**Issue by StanKocken** [googlesamples/android-vision#274]
Play Service Barcode Scanner doesn't work when we set targetSandboxVersion to 2.

Condition:
- Use an Android device with API 26

Step to reproduce:
1- take the sample app from https://github.com/googlesamples/android-vision
2- update to use API 26 as target
3- add `android:targetSandboxVersion="2"` into the AndroidManifest.xml

Expected:
- Logcat will print
I/Vision: Loading library libbarhopper.so
I/Vision: libbarhopper.so library load status: true
- QR code recognised

Actual result:
- Logcat will print
I/Vision: Loading library libbarhopper.so
I/Vision: libbarhopper.so library load status: false
- no QR code recognised 

Note: if you don't add `android:targetSandboxVersion=2`, then everything is working as expected.

**Comment by pchx** [comment]
Thanks for the report. We're looking into it.

Do you need sandbox v2 for any particular reason, or are you using it because the Play Store suggests using it?

**Comment by StanKocken** [comment]
Thanks for looking into it.
We use it because it is mandatory for InstantApp.

**Comment by StanKocken** [comment]
Any news on this issue?
Note: I opened the issue on the Google tracker as well, as I'm not sure if it's a library or a platform issue https://issuetracker.google.com/issues/67623690

**Comment by pchx** [comment]
Hi, you shouldn't need to set targetSandboxVersion=2 just yet. The recommendation to do so was apparently sent in error:

https://stackoverflow.com/questions/46178636/when-publish-instant-appinvalid-target-sandbox-version

**Comment by StanKocken** [comment]
@pchx once you have this flag, you cannot remove it, otherwise Android O devices cannot update your application.
So I will have this issue with the vision API forever?

**Comment by pchx** [comment]
My understanding is that the sandbox version cannot be downgraded once you've pushed to the Play Store. Sorry about this -- Developer Relations will be in contact with your team directly.

**Comment by StanKocken** [comment]
I can confirm that this issue has been fixed with 8.1 MR2
