### ISSUE TITLE
how to disable text recognizer multi detect?

### ISSUE THREAD

**Issue by pourya0111** [googlesamples/android-vision#279]
hey there i used this samples and they are awsome however i'm looking for some way to detect texts lonely (not multi detect process) right now it wil draw graphics and detect as much as texts in screen
and also is there anyway to detect only integers?
and one last thing is is there any way to create  a something like a window frame on camera preview to only show and recognize things inside that window frame?(i think you saw the barcode readers that detects barcodes only inside a square frame :))
thanks

**Comment by liuyl** [comment]
Currently text recognizer detects as much texts as it can on the whole screen, you'll need to write your own post processor if you only need integers or text at a specific location.
