### ISSUE TITLE
Error PDF417

### ISSUE THREAD

**Issue by DanielVargasRomero** [googlesamples/android-vision#290]
Hi

I'try scan a PDF417 barcode, a throw this exception

JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0x85
A/art: art/runtime/java_vm_ext.cc:470]     string: '0333562423����������������������������PubDSK_1����������������404433����1017230182MEJIA������������������������������������ALVAREZ��������������������������������GLORIA����������������������������������ALEJANDRA����������������������������0F19950426012950A+��2+��rRÿ@;z<?¡ o|jo®v~áz{~àx¡p¨bFlIg3£bZ{²lÅl"e]e¬~Ñf²¹ÕÖGscu7kb�PyEuZH~¦ÿ{jõû¿¥HfJÿ��������������������������������������������������������������������������������������������������������7%��SRÿInBuIqXnH|hxÛz\¾~Îå°~{¥uS|mcj|tqi~v¦maxq¾Çh[a h¨*d4xU¥«îj½ÿ¿6Ó4ýÑù����������������������������������������������������������������������������������������������������������������������������������C\ £süiì´È]Ñb=²àVÀ½ç]@×+û.Âý¢èÜ®ÙÖ'
A/art: art/runtime/java_vm_ext.cc:470]     input: '0x30 0x33 0x33 0x33 0x35 0x36 0x32 0x34 0x32 0x33 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0x50 0x75 0x62 0x44 0x53 0x4b 0x5f 0x31 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0x34 0x30 0x34 0x34 0x33 0x33 0xc0 0x80 0xc0 0x80 0x31 0x30 0x31 0x37 0x32 0x33 0x30 0x31 0x38 0x32 0x4d 0x45 0x4a 0x49 0x41 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0x41 0x4c 0x56 0x41 0x52 0x45 0x5a 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0x47 0x4c 0x4f 0x52 0x49 0x41 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80 0xc0 0x80
A/art: art/runtime/java_vm_ext.cc:470]     in call to NewStringUTF

**Comment by pchx** [comment]
Duplicate of #221.
