### ISSUE TITLE
Text Dectection can return text in arbitrary order

### ISSUE THREAD

**Issue by drgottjr** [googlesamples/android-vision#299]
Under certain circumstances, 	SparseArray<TextBlock> textBlocks = detector.detect(frame) is either extracting text in some artibrary order and/or storing it arbitrarily in such a way that the text cannot be output in correct sequential order.

Look at the attached image.  Then look at the output from MobileVision and from Tesseract.  MobileVision's output is not displayed top to bottom.  Tesseract's output is displayed top to bottom.

I can't always duplicate the issue (ie, by photographing similarly presented text snippets), but mostly I can.  In every case, Tesseract will read top to bottom (even though the error rate might be a little higher).  

Whether or not MobileVision's detector is trained to read top to bottom I can't say for sure, but the use of the SparseArray seems to be involved.

Below please find some log entries:

This is what the SparseArray holds.  Note the keys.
HASH: {3=com.google.android.gms.vision.text.TextBlock@2fcceb9, 
              4=com.google.android.gms.vision.text.TextBlock@28b692fe, 
              5=com.google.android.gms.vision.text.TextBlock@24fa2a5f, 
              7=com.google.android.gms.vision.text.TextBlock@1be72cac, 
              9=com.google.android.gms.vision.text.TextBlock@a129d75, 
            12=com.google.android.gms.vision.text.TextBlock@3364e10a}

There are 2 ways to step through the hash: either by using an index into the hash or by accessing the value of a hash entry by calling up its key.  These methods are effectively the same.

Here is the value (ie, text) held in each element of the hash.  We see the index used to step through the hash, the corresponding key of that element and the corresponding value (text) in that element:
block 0: key: 3, value: hate, but individual
block 1: key: 4, value: convinced, thanks to a sense of historical
block 2: key: 5, value: DEBORAH FELDMAN AUTHOR
block 3: key: 7, value: In Germany, I've certainly encountered
block 4: key: 9, value: courage, as well, from people who are
block 5: key: 12, value: responsibility, of the need to take a stand against hatred.

Note that the element held by block 3 has key 7 and value "In Germany, I've certainly encountered".
These are the first words of the text in the image.  There is no way to put them at the start of the text.
If you simply step through the hash with an index (0 to size - 1), you won't see the first words of the text until you reach the 4th block.  and although you can ask which key is held in the 4th block (block 3), there is no way to know that the element with key 7 is supposed to be output first.

Normally, a hash is not maintained in any discernible order and access is meant to be by key, but in this case knowing that key 7 is in the 4th block is of no help, since we don't know that key 7 is supposed to be the first one we should look at.  sorting the keys serves no purpose, and sorting the values is a waste of time.

If the image were multi-columnar and/or with heavy noise to confuse the extractor, I would expect jumbled output.  But that Tesseract - supremely susceptible to noise or stray characters implying another column somewhere - can figure out a simple top to bottom read, leads me to guess that the bug (if bug there is) is in how the detector assigns the hash keys.  It doesn't matter where the element with the first line of text is stored in the array, it just has to have the lowest key (otherwise, you don't know it's supposed to come first).  It doesn't have to be the 0th key, it just has to be the lowest key.  Non-text portions of the image have a right to be identified by key (even though they contain no text), but assigning key 7 to the first text line and key 3 to some line that comes after it makes no sense.  In fairness, the detector can assign keys however it sees fit, but there has to be some way for the developer to know the actual text order.

MOBILEVISION OUTPUT AS A WHOLE BLOCK:
 hate, but individualconvinced, thanks to a
sense of historicalDEBORAH FELDMAN
AUTHORIn Germany, I've
certainly encounteredcourage, as well, from
people who areresponsibility, of the
need to take a stand
against hatred.

-------------------------------
TESSERACT'S OUTPUT:
 ‘ln Germany, I’ve
certainly encountered
hate, but individual
courage, as well, from
people who are
convinwd, thanks to a
sense of historical
responsibility, of the
need to take a stand
against hatred.’
DEBORAH mom
AUTHOR

You should find the original image here:
![screencap](https://user-images.githubusercontent.com/11996562/34278475-08dd01ac-e679-11e7-9f4b-b79bd8937205.png)

Thanks for taking the time to read this.
-go

**Comment by drgottjr** [comment]
i must have posted this to the wrong group, sorry.  i figured out a workaround.  no harm, no foul

**Comment by kelvohh** [comment]
drgottjr how did you solve this. i am having the same issue

**Comment by drgottjr** [comment]
you can't.  at least not until somebody higher up the food chain takes notice.  good luck trying to get google's attention.  but you can improve things a little.  it's not really enough for me, so there is little choice but to wait.  on the plus side, it is fast as hell and mostly right.  that may or may not be enough to tip the scales in its favor.
there are 2 main issues (which you may already know): 1) for whatever reason, mobile vision uses a hash to store each block of text recognized.  they call it a sparse array, but that implies it's something that it's not.and 2) a "line" of text for mobile vision isn't exactly what we think a line is (maybe you - like me - have spent too much time with tesseract).  in other words, not only can the blocks be out of order (due to the futility of trying to treat a hash like an array), but the lines of text within each block can be whack, as well.  i'll spare you the rest of the lecture and show you what i did to mitigate the damage:i'll assume you recognize what's going on in the code.  let me know otherwise.
if (textRecognizer.isOperational()) {
   Frame frame = new Frame.Builder().setBitmap(bitmap).build();
   SparseArray<TextBlock> textBlocks = textRecognizer.detect(frame);
   String lines = "";
   ArrayList<Textholder> tholder =new ArrayList<Textholder>();  // DECLARE A LIST FOR USE LATER   for (int index = 0; index < textBlocks.size(); index++) {
      int key = textBlocks.keyAt(index);
      TextBlock tBlock = textBlocks.valueAt(index);
      if (tBlock != null) {                                         // block is valid, get its components (ie, lines)
         for (Text line : tBlock.getComponents()) {    // step through each line in the block
            float top = line.getBoundingBox().top;       // CAPTURE THE LINE'S BOUNDING BOX & ITS TOP COORD !!
            Textholder t = new Textholder(top,line.getValue());  // STUFF top AND THIS LINE'S text INTO AN ELEMENT FOR YOUR LIST
            tholder.add( t );    // ADD THAT ELEMENT TO YOUR LIST
         }
      }
   }
   if (textBlocks.size() == 0) {            // THERE WAS NO TEXT FOUND.  YOU COULD PUT THIS TEST EARLIER IF YOU WANTED            // PRESUMABLY, YOU EXIT IN THIS CASE
   } 
   else {     // OTHERWISE, YOU DO HAVE SOME TEXT
      Collections.sort( tholder );    // SORT YOUR LIST USING THE top VALUE OF EACH ELEMENT AS YOUR SORT FIELD.  THIS ASSURES THAT YOU WILL AT LEAST BE READING TOP TO BOTTOM.  BUT IT DOESN'T GUARANTEE MOBILE VISION SEES A LINE OF TEXT THE WAY WE DO
      for (int i = 0; i < tholder.size(); i++) {
         Textholder tt = tholder.get( i );
         lines = lines + tt.getText() + "\n";
      }
      // DO WHATEVER YOU WANT WITH lines.  IT'S JUST A LINEFEED DELIMITED STRING       }             textRecognizer.release();       
}  // if textRecognizer ok

-go

**Comment by DeraDeveloper** [comment]
What is Textholder

**Comment by drgottjr** [comment]
just a class to hold the upper left coordinate of a text block and the text in the box.  sorry, i failed to include it in the code.
as mentioned in my previous explanation, the only (mostly) reliable way to know where each line of text appears in the ocr'd document is to use its topmost left coordinate within the document.  google vision's implementation doesn't do that.  as a result, what might be line 3 appears as the 0th element in google's list of blocks.  if you simply step through google's list of blocks, you would end up showing line 3 as the first line of text.  i worked with it enough to know that it was the case when i was testing google's text detection.  it was easy to demonstrate.  you couldn't step through the list by index, and you couldn't step through it by using whatever object it was that the index pointed to.
the closest i could come to overriding that behavior was to create my own list of blocks and store a text line's coordinates along with the text.  i then used the coordinates as the sort field.  the assumption being that if you sorted the lines based on their coordinates within the document, your output would be top to bottom.  for whatever reason, google bases its ordering on some other factor.  in most cases, google's output is fine, but not always.  i couldn't figure out a pattern in order to replicate the behavior, but when the behavior occurred, it was easy to see what was happening and to make it happen over and over with the same document and to figure out some kind of solution to override the behavior.
side note: i'm an old c programmer.  i apologize for failing to disguise that mindset in any java code i had to write to make the thing work.



 class Textholder implements Comparable<Textholder>{ //public class Textholder {     private float Y;      private String text;        Textholder(float Y, String text) {           this.Y=Y;           this.text = text;       }      String getText() {          return text;     }      float getY() { return Y;      }  public int compareTo(Textholder th) {     if (Y == th.getY())     return 0;     else if (Y > th.getY())      return 1;     else       return -1; } }


- go
    On Tuesday, May 8, 2018, 11:33:25 AM EDT, Chidera <notifications@github.com> wrote:  
 
 
What is Textholder

**Comment by DeraDeveloper** [comment]
Thanks it worked.

**Comment by drgottjr** [comment]
more like worked(around), i'm sorry to say.  good old plain tesseract - for all its problems - never failed to read top to bottom.  its child is blindingly fast, if slightly dyslexic.
    On Wednesday, May 9, 2018, 4:16:22 PM EDT, Chidera <notifications@github.com> wrote:  
 
 
Thanks it worked.
