### ISSUE TITLE
com.google.android.gms.samples.vision.ocrreader.ui.camera.GraphicOverlay doesn't exist in play-services-vision:11.8.0

### ISSUE THREAD

**Issue by THEAccess** [googlesamples/android-vision#324]
The GraphicOverlay<T> used in OcrDetectorProcessor doesn't exist in play-services-vision:11.8.0, what to use instead?

**Comment by mukarramali** [comment]
That is a sample application, If you are using it, copy it in your own project and then replace the package name to yours.
Ex: com.yourpackage.pojecta.ui.camera.GraphicOverlay
