### ISSUE TITLE
Switch Back camera to Front camera by onClick button ?

### ISSUE THREAD

**Issue by vlasevich** [googlesamples/android-vision#341]
Can I switch cameras by onClick() ? To change .setFacing(CameraSource.CAMERA_FACING_FRONT) ?

**Comment by mohsinhussain** [comment]
Yes for sure. Please find the code below that works like a charm on my device. Add the following Button onclicklistener in your **OnCreate()** function in FaceTrackerActivity;

`changeCameraButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(mCameraSource.getCameraFacing()==CameraSource.CAMERA_FACING_FRONT){
                    changeCameraButton.setText("FRONT CAMERA");
                    if (mCameraSource != null) {
                        mCameraSource.release();
                    }
                    createCameraSource(CameraSource.CAMERA_FACING_BACK);
                }
                else{
                    changeCameraButton.setText("BACK CAMERA");
                    if (mCameraSource != null) {
                        mCameraSource.release();
                    }
                    createCameraSource(CameraSource.CAMERA_FACING_FRONT);
                }

                startCameraSource();
            }
        });`

Update the **createCameraSource()** function to take the parameter reflecting camera facing source;
`private void createCameraSource(int cameraFacing) {

        Context context = getApplicationContext();
        FaceDetector detector = new FaceDetector.Builder(context)
                .setClassificationType(FaceDetector.ALL_CLASSIFICATIONS)
                .build();

        detector.setProcessor(
                new MultiProcessor.Builder<>(new GraphicFaceTrackerFactory())
                        .build());

        if (!detector.isOperational()) {
            // Note: The first time that an app using face API is installed on a device, GMS will
            // download a native library to the device in order to do detection.  Usually this
            // completes before the app is run for the first time.  But if that download has not yet
            // completed, then the above call will not detect any faces.
            //
            // isOperational() can be used to check if the required native library is currently
            // available.  The detector will automatically become operational once the library
            // download completes on device.
            Log.w(TAG, "Face detector dependencies are not yet available.");
        }

        mCameraSource = new CameraSource.Builder(context, detector)
                .setRequestedPreviewSize(640, 480)
                .setFacing(cameraFacing)
                .setRequestedFps(30.0f)
                .build();
    }`

Here is my update in the layout of FaceTrackerActivity;

`<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/topLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true">

  <com.google.android.gms.samples.vision.face.facetracker.ui.camera.CameraSourcePreview
      android:id="@+id/preview"
      android:layout_width="match_parent"
      android:layout_height="match_parent">

    <com.google.android.gms.samples.vision.face.facetracker.ui.camera.GraphicOverlay
        android:id="@+id/faceOverlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

  </com.google.android.gms.samples.vision.face.facetracker.ui.camera.CameraSourcePreview>

  <Button
      android:id="@+id/changeCameraButton"
      android:text="Back Camera"
      android:layout_alignParentBottom="true"
      android:layout_centerHorizontal="true"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content" />

</RelativeLayout>`

I hope this helps. Cheers!

**Comment by vlasevich** [comment]
What is this method `startCameraSource();`?

**Comment by vlasevich** [comment]
I have found answer for my question. I just called my init() method with FRONT param and recall **CameraSource.start(visionCameraView.getHolder());**
 and it's worked

**Comment by nitin6542** [comment]
i want to make camera source to IP camera HOw can i do that

**Comment by AdityaPratapSinghR** [comment]
> I have found answer for my question. I just called `mCameraSource.release(); ` my `init()` method with `FRONT` param and recall **CameraSource.start(visionCameraView.getHolder());**
> and it's worked
Bro where to call this method. I am doing Camerasource.release but my app crashes. Can you please elaborate?

**Comment by vlasentiy** [comment]
@AdityaPratapSinghR   
 ```
private var cameraSource: CameraSource? = null
...
onViewCreated(...){
       cameraSource = CameraSource(activity ?: return)
}

fabSwitchCamera?.setOnClickListener {
            cameraSource?.setFacing(if (cameraSource?.cameraFacing == CameraSource.CAMERA_FACING_BACK) CameraSource.CAMERA_FACING_FRONT else CameraSource.CAMERA_FACING_BACK)
        preview?.stop()
        startVisionCameraSource()
        }

private fun startVisionCameraSource() {
        try {
            preview?.stop()
            preview?.start(cameraSource)
        } catch (e: IOException) {
            logger.e(e)
            cameraSource?.release()
        }
    }
```
