### ISSUE TITLE
Disable automatic PDF417 parsing

### ISSUE THREAD

**Issue by remi-bast** [googlesamples/android-vision#346]
Hi,

The Barcoce API documentation says: "It automatically parses QR Codes, Data Matrix, PDF-417, and Aztec values" / "Barcodes that contain structured data (commonly done with QR codes) are parsed".

Is there any option to disable this automatic parsing and get the raw value only?

Issue behind my question: I need to get PDF417 value, but this PDF417 is not detected. I assume that it is not detected because it cannot be parsed (I know that the value of this PDF417 does not follow any specific standard).

**Comment by remi-bast** [comment]
Hi,

As scanning does not work, does it mean that my PDF417 is not correct?

**Comment by Mavbraz** [comment]
Hi,

It may be. Have you tried scan your bar code any other way?
Try this to verify: https://online-barcode-reader.inliteresearch.com

**Comment by remi-bast** [comment]
Hi,

I have verified with above link. It can be read and identifyed successfully as "Type: Pdf417".

Also tested successfully with PDF417 Android app from Microblink downloaded from Android market.

**Comment by pchx** [comment]
In the Barcode API, reading the barcode (getting a raw value from an image) and parsing the value are separate. We will return a result even if the raw value couldn't be parsed.
