### ISSUE TITLE
Camera view Barcode Reader not full width

### ISSUE THREAD

**Issue by Pieteru87** [googlesamples/android-vision#373]
Camera view of barcode reader example not full width to screen
This the picture of problem:
https://drive.google.com/file/d/145cmmBUav3HvrDuQgp-SS3r_vrvUnRQl/view?usp=sharing

**Comment by pchx** [comment]
Intentional behavior.

The camera frame and display may not have exactly the same aspect ratio, so the camera view sizes itself to fill as much of the display as it can without stretching.

**Comment by Pieteru87** [comment]
How can i fix the code? 
this is the part of BarcodeCaptureActivity.java

`private CameraSource mCameraSource;`
`CameraSource.Builder builder = new CameraSource.Builder(getApplicationContext(), barcodeDetector)`
    `.setFacing(CameraSource.CAMERA_FACING_BACK)`
    `.setRequestedPreviewSize(1600, 1024)`
    `.setRequestedFps(30.0f);`
`mCameraSource = builder.build();`

if I change "setRequestedPreviewSize()" with any size 
it not give an effect.

**Comment by NasH5169** [comment]
Hi,

I've already think about this sample limitation.

You can put the screen size in the request preview size, but it is not garantee that the screen size exists in the camera available sizes (i.e validPreviewSizes)

```
DisplayMetrics metrics = new DisplayMetrics();
getWindowManager().getDefaultDisplay().getMetrics(metrics);

mCameraSource = new CameraSource.Builder(getApplicationContext(), barcodeDetector)
                .setFacing(CameraSource.CAMERA_FACING_BACK)
                .setRequestedPreviewSize(metrics.heightPixels, metrics.widthPixels)
                .setRequestedFps(20.0f)
                .setFocusMode(autoFocus ? Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE : null)
                .setFlashMode(useFlash ? Camera.Parameters.FLASH_MODE_TORCH : null)
                .build();
```

Another workaround is to get the max preview size available in CameraSource.java

Like the comment said, the algo needs to be improved to search matching screen size and preview size. It is about "ratio matching".

```
private static SizePair selectSizePair(Camera camera, int desiredWidth, int desiredHeight) {
        List<SizePair> validPreviewSizes = generateValidPreviewSizeList(camera);

        // Use the desired size to improve the algorithm to find the closest camera preview size from screen size
        Log.d(TAG, "desiredSize = " + desiredWidth + " / " + desiredHeight);

        // Simple algorithm, get the pair with the tallest edge
        SizePair selectedPair = validPreviewSizes.get(0);
        int maxEdge = 0;
        for (SizePair sizePair : validPreviewSizes) {
            if (sizePair.previewSize().getWidth() > maxEdge) {
                selectedPair = sizePair;
                maxEdge = sizePair.previewSize().getWidth();
            }

            if (sizePair.previewSize().getHeight() > maxEdge) {
                selectedPair = sizePair;
                maxEdge = sizePair.previewSize().getHeight();
            }
        }

        return selectedPair;
    }
```
