### ISSUE TITLE
Drone camera

### ISSUE THREAD

**Issue by il421** [googlesamples/android-vision#377]
Is it possible to use drone camera feed to build barcode detection + scanning App ? What kind of problems can I face?

**Comment by pchx** [comment]
No reason why it wouldn't work, assuming your drone is able to capture images of sufficient quality.

Let us know how it goes.

**Comment by il421** [comment]
Hi again... I have some difficulties with the implementing. I use the way, but it is very slow. And it the way the recognition is not good. For our project, we use DJI Phantoms 4 and their Mobile SDK.

    private void recognizeBarcode(Frame frame) {
        SparseArray<Barcode> barcodes = barcodeDetector.detect(frame);

        if (barcodes.size() > 0) {
           // Some actions
        }
    }

    @Override
    public void onSurfaceTextureUpdated(SurfaceTexture surface) {
        frame = new Frame.Builder().setBitmap(mVideoSurface.getBitmap()).build();

        recognizeBarcode(frame);
    }

**Comment by il421** [comment]
DJI SDK allows building an app with video feeder via TextureView. That is why I am using the way, that I mentioned above. I understand why it is slow. Could you give me an advice on how to use Google APIs for Android.
