### ISSUE TITLE
Out of Memory exception after starting and stopping the camera several times.

### ISSUE THREAD

**Issue by Syzygy2048** [googlesamples/android-vision#38]
I noticed that if you start and stop the camera several times, the memory fills up until you get an OOM exception. After some investigating with the memory profiler I noticed that there's a huge hash map that keeps getting bigger, namely mBytesToByteBuffer.
The reason for that is that mBytesToByteBuffer is never cleared when CameraSource is paused, but when createCamera() is called, 4 new fairly large byte buffers are created.

My fix is to call mBytesToByteBuffer.clear() in createCamera() right before the 4 calls to camera.addCallbackBuffer(mPreviewSize);

**Comment by pm0733464** [comment]
Yes, this issue was recently discovered by another developer.  See the pending change below.  I'll try to get this committed today.

https://github.com/googlesamples/android-vision/pull/35#issuecomment-146794685

**Comment by Syzygy2048** [comment]
Whoops, alright, I guess this can be closed then. Thank you.
