### ISSUE TITLE
Google Barcode Api Shows Weird Leak With Leak Canary Only on Real Devices

### ISSUE THREAD

**Issue by paourissi** [googlesamples/android-vision#389]
I use Google's Barcode api to read qr codes and i also use Leak Canary to detect memory leaks. On emulators there is no memory leak shown. When i run on a real Device Android Xiaomi MI8 and Samsung Galaxy TAB E i get this weird memory leak.

Is it a memory leak or a library's bug?

debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.6.1'
releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.6.1'
implementation 'com.google.android.gms:play-services-vision:16.2.0'

Here is also my ScanCode Class:

  public ScanProcess(final FragmentActivity activity){

    cameraView = activity.findViewById(R.id.cameraView);
    cameraView.setZOrderMediaOverlay(true);

    barcode = new BarcodeDetector.Builder(activity)
            .setBarcodeFormats(Barcode.QR_CODE)
            .build();

    try{
        if(!barcode.isOperational()){
            Toast.makeText(activity, "Wait a few seconds until download complete. If persists, Restart app OR Update Google Play Services", Toast.LENGTH_LONG).show();
		    ((BindingCallback)activity).setVisibility(true);
            activity.getSupportFragmentManager().popBackStack();
            return;
        }
    }catch (Exception e){
            Log.d("Exception",e.toString());
            Toast.makeText(activity, "Update Google Play Services.", Toast.LENGTH_SHORT).show();
    }

    cameraSource = new CameraSource.Builder(activity, barcode)
            .setFacing(CameraSource.CAMERA_FACING_FRONT)
            .setRequestedFps(24)
            .setAutoFocusEnabled(true)
            .setRequestedPreviewSize(1920,1080)
            .build();

    cameraView.getHolder().addCallback(new SurfaceHolder.Callback() {
        @Override
        public void surfaceCreated(SurfaceHolder holder) {
            try{
                if(ContextCompat.checkSelfPermission(activity, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED){
                        cameraSource.start(cameraView.getHolder());
                }
            }
            catch (Exception e){
                Toast.makeText(activity, "Can't Acquire Camera Service", Toast.LENGTH_LONG).show();
                activity.finish();
            }
        }

        @Override
        public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {

        }

        @Override
        public void surfaceDestroyed(SurfaceHolder holder) {
            cameraSource.release();
        }
    });

    barcode.setProcessor(new Detector.Processor<Barcode>() {

        @Override
        public void release() {

        }

        @Override
        public void receiveDetections(Detector.Detections<Barcode> detections) {
            final SparseArray<Barcode> barcodes =  detections.getDetectedItems();
            if(barcodes.size() > 0){

                }
            }
        }
    });
	

}

![inkedscreenshot_2018-10-15-19-01-13-943_com paourissi ehr_li](https://user-images.githubusercontent.com/5431858/47000300-a3b53f80-d130-11e8-941f-39c09c99b4b4.jpg)
![screenshot_2018-10-15-19-04-11-811_com paourissi ehr](https://user-images.githubusercontent.com/5431858/47000303-a6179980-d130-11e8-825c-bcf6bd3701db.png)

@tjohns @dav-cz @keyboardsurfer @incon

**Comment by ViktorMorgachev** [comment]
Have a nice day, i have this problem also, but i don't know how to solve it, please help me. My program is so small.
https://github.com/ViktorMorgachev/BarcodeScannerDemo

**Comment by isnalla** [comment]
For reference: The solution is to pass `ApplicationContext` to `BarcodeScanner.Builder` and `CameraSource.Builder` instead of the `Activity`, as seen in the vision api sample.
https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/BarcodeCaptureActivity.java
