### ISSUE TITLE
Code 128 (25 length) not detected

### ISSUE THREAD

**Issue by JohanLeDong** [googlesamples/android-vision#398]
Hi there,

I have code NMI00001/2018/01/00000102 ([link image barcode](https://barcode.tec-it.com/barcode.ashx?data=NMI00001%2F2018%2F01%2F00000102&code=Code128&multiplebarcodes=false&translate-esc=false&unit=Fit&dpi=96&imagetype=Gif&rotation=0&color=%23000000&bgcolor=%23ffffff&qunit=Mm&quiet=0&eclevel=L)) but camera not detected.

Please check issue!

Thanks,

**Comment by pchx** [comment]
Code128 codes require a quiet zone around the barcode. Note that your example is set over a black background and so the outermost bars on either end blend into the background.

Luckily, your barcode generator has a parameter for setting the quiet zone size ("quiet=5"):

https://barcode.tec-it.com/barcode.ashx?data=NMI00001%2F2018%2F01%2F00000102&code=Code128&multiplebarcodes=false&translate-esc=false&unit=Fit&dpi=96&imagetype=Gif&rotation=0&color=%23000000&bgcolor=%23ffffff&qunit=Mm&quiet=5&eclevel=L

With that small change, the example you provided is easily read.

**Comment by JohanLeDong** [comment]
Hi pchx,

Yeah! Camera is working. 

Thank you!
