### ISSUE TITLE
Barcode is not detected if it contains all spaces.

### ISSUE THREAD

**Issue by apvasanth03** [googlesamples/android-vision#40]
If i have barcode with all spaces then it is not detected.
For example if we have barcode "      ", then it is not detected.

**Comment by pchx** [comment]
Which barcode formats are you seeing this issue with? What use case is there for recognizing a barcode containing only spaces?

**Comment by apvasanth03** [comment]
1. Barcode format I am using code 128
2. There is no specific case, we are using vision api for barcode scanning in our application and during random testing it fails.
3 And also kindly replay to issue
https://github.com/googlesamples/android-vision/issues/12

**Comment by pchx** [comment]
The barcode API is capable of reading Code 128 with six or more spaces. For example, this image works:

![code-128-spaces](https://cloud.githubusercontent.com/assets/13904899/10617688/be38c894-7739-11e5-9d5d-05e71da93c86.jpg)

You were running into the limitation covered by #12 if you were trying to recognize a code containing just a single space.

**Comment by apvasanth03** [comment]
Thanks pchx for your replay.

I think I must have tried with less than 6 white spaces.

But issue 
https://github.com/googlesamples/android-vision/issues/12
Is preventing us from using Google vision api

Can you provide us any fix for it.
