### ISSUE TITLE
US Driver License scanning issues with PDF417 format

### ISSUE THREAD

**Issue by samworldllc** [googlesamples/android-vision#449]
i am facing some issues with Sample FL driver license... when i try to write my own florida license and scan it . it shows only name in app and DL , DOB , EXPIRY shows data not encoded...but when i analyze the barcode via some online scanner it shows me complete data inside pdf417 now point is why app not showing other details ? is there any problem with encoder ? or i have to specify the location for barcode.

**Comment by richmogul72** [comment]
Did you resolve this? I'm trying to convert my PDF417 data into barcode. But I haven't been successful. Can you help out?
