### ISSUE TITLE
android - vision not recognize qr code of around more than 300 character in lower mega pixel camera like 3.2 mega pixel even in 5 mega pixel.

### ISSUE THREAD

**Issue by rohitbandil** [googlesamples/android-vision#49]
I have using this library but my qr image contains 300 to 500 character information so i have tested on 8 mega pixel it is easy to recognize the qr image but in 3.2 or even in 5 mega pixel camera is not recognizing.please provide me any solution i am awaiting for the answer.

**Comment by pchx** [comment]
More information would be helpful.

Do you have example images of the codes you're having trouble recognizing? When you capture 8MP vs. 3.2/5MP images, are you using the same camera (configured differently), or different models? Do you have autofocus enabled?

**Comment by rohitbandil** [comment]
Thanks for your reply but I got the solution for this problem actually the was why the camera of 3.2 and 5 mgp was unable to recognise if qr image contains  around 300 or more character because that image dimension was low around 300 px but as soon as I increase the image dimension I was able to the recognise that qr code. So be careful while generating a long character qr your qr should be big.

**Comment by rohitbandil** [comment]
Thanks for your reply but I got the solution for this problem actually the issue  was why the camera of 3.2 and 5 mgp was unable to recognise if qr image contains  around 300 or more character because that image dimension was low around 300 px but as soon as I increase the image dimension device was able to the recognise that qr code. So be careful while generating a long character qr your qr image should be big. But 3.2  mgp camera was unable recognise qr image that contains more than 300 character even though the imadimensiontion is big.
