### ISSUE TITLE
Extracting full details (eg. pixel positions) for the detected face features using Vision API 

### ISSUE THREAD

**Issue by vinaykumar2491** [googlesamples/android-vision#61]
How to extract the details like pixel positions of the detected features while using Vision API.
I think the details should be in 'faces' :

SparseArray<Face> faces = faceDetector.detect(frame);

Thanks for Help

**Comment by pm0733464** [comment]
See the photo-demo sample for an example.  First, the detector needs to be setup for detecting facial landmarks:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/photo-demo/app/src/main/java/com/google/android/gms/samples/vision/face/photo/PhotoViewerActivity.java#L63

Detected facial features are returned as Landmark objects, which have an associated pixel position:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/photo-demo/app/src/main/java/com/google/android/gms/samples/vision/face/photo/FaceView.java#L96

**Comment by vinaykumar2491** [comment]
Thanks. That helped. 
But how can I identify which pixels correspond to what (whether its the eyes/lip-regions/nose etc)?

**Comment by vinaykumar2491** [comment]
Solved it using inbuilt functions that provide the pixel details like: 
Landmark.BOTTOM_MOUTH; etc

Thanks

**Comment by vinaykumar2491** [comment]
![equation](http://latex.codecogs.com/gif.latex?1%2Bsin%28mc%5E2%29%0D%0A)
