### ISSUE TITLE
barcodeDetector.isOperational() is always false and not finishes download 

### ISSUE THREAD

**Issue by vbuberen** [googlesamples/android-vision#63]
The problem appears to happen on Nexus 5X. I use vision for barcode scanning, but the thing is it can`t download required native libraries to enable scanning. Other devices like Nexus 5, Sony Xperia M, Nexus 4, Nexus 7 2012 (yeah, it also can scan barcode with its front camera) work fine.
The process of downloading starts, as I can see from logcat:

```
02-09 11:57:37.767 22844-22844/------.android.develop I/Vision: Supported ABIS: [arm64-v8a, armeabi-v7a, armeabi]
02-09 11:57:37.769 22844-22844/------.android.develop I/Vision: Requesting barcode detector download.
02-09 12:12:17.074 28129-28129/------.android.develop W/Barcode-reader: Detector dependencies are not yet available.
```

But it never ends and hasLowStorage check isn`t triggered. App have all permissions and access to network. Logcat shows no more info about vision or downloading. Only warnings like the last one I have provided here. Also added dependency to AndroidManifest file as it suggested in documentation for vision api - nothing changed.
Any suggestions or information about when it is going to be fixed?

**Comment by michalciolek** [comment]
I also have a Nexus 5X but for me it works like a charm.
`Stock Android 6.0.1 & com.google.android.gms:play-services:8.4.0`

**Comment by ggirard07** [comment]
Is this the "serious bug" mentioned in v9.0 release notes?

**Comment by clivejefferies** [comment]
I have this problem too. This is seems to be device specific. Works on the Nexus 5, but not Sony Z5 Compact.

**Comment by eeVoskos** [comment]
Same here on a Nexus 5X running stock Android 6.0.1 with Google Play Services apk v9.2.56. I'm using the latest `com.google.android.gms:play-services-vision:9.2.1` dependency.
