### ISSUE TITLE
QR codes generated from internal iOS library cannot be scanned

### ISSUE THREAD

**Issue by kenticus** [googlesamples/android-vision#66]
This library allows me to scan the majority of QR codes out there....however, the iOS team at my company generates their QR codes from an internal lib in iOS. Here's the link: [https://developer.apple.com/library/prerelease/ios/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CIQRCodeGenerator](url)

Here is the QR code it generates:
![image](https://cloud.githubusercontent.com/assets/4250025/13232726/a81f30d4-d96d-11e5-88ca-2a0708870807.jpeg)

Any idea why the vision api can't read this??

Thanks,
Kent

**Comment by kenticus** [comment]
Here is one we generate on android....and it gets scanned perfectly.
![qrcode 2](https://cloud.githubusercontent.com/assets/4250025/13443160/1e384058-dfbd-11e5-9f70-d3dc86a31d19.png)

**Comment by pchx** [comment]
Thank you for reporting this issue.

The example from CoreImage fails once it hits our decoder's error correction stage. We're looking into why.

**Comment by pchx** [comment]
What error correction level (L, M, Q, or H) are you generating the QR code with?

Would you mind trying to scan codes with values for inputCorrectionLevel?

**Comment by ggirard07** [comment]
The problem is due to the mirroring applied on the QR Code (mirrored 180deg). Take a look at the alignment point, once rotated to normal position it will be placed at the lower left corner where as it should be at the lower right corner.

I do not know if it is a requirement in the QR code standard or not...

But third party libraries like Manatee, Scandit or ZXing are capable to scan 180deg mirrored QR code where as Google vision is not.

**Comment by rockredbones** [comment]
The QR code above is generated with H correction level and UTF8 encoding. But I have also tried using L,M and Q with both UTF8 and Latin-1 encodings and neither of them worked.

**Comment by kenticus** [comment]
Inverting the iOS QR code by 180 degrees vertically makes it so it can get scanned. It would be nice if this lib checked that automatically like other 3rd party libs.

**Comment by pchx** [comment]
Yes, we'd definitely like to provide automatic support for mirrored codes.

It seems other libraries attempt to mirror the bit matrix and retry decoding, which has a latency cost. One of the key features of our barcode API is its speed, so we're looking into ways to provide this feature with less of a latency penalty.

**Comment by pchx** [comment]
The latest version of our Barcode API (part of [Google Play Services 10.0](https://developers.google.com/vision/release-notes#google_play_services_100)) adds support for mirrored QR codes.

Thanks for your patience!
