### ISSUE TITLE
Tracking ean-13 barcodes using the detector from image. 

### ISSUE THREAD

**Issue by zigge** [googlesamples/android-vision#67]
HI. 

I've come across a problem. I am trying to build an app that takes a image, from the camera, and saves the image to a temp img, but the app can only detect qr codes... I was wondering about if it was the res of the image that I was saving in. Then i tried to prevent android from scaling the image, bitmap, and loading the original image as it was taking from the camera, intro the decoder to decode the barcode. But without any luck.. The I was thinking, what if I took a image from the internet and saved it as a bitmap in the res/drawable folder, and then load it via the BitmapFactory in android.. But, again, without any luck... So my conclusion is that it's either the code I wrote that do not work, or it is the decoder that cannot track the barcode from a steady img, rather from a stream of images like the camera preview. 

The code I've used: 

`       public class BarcodeTracking extends Activity {
        private static final int CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE = 100;
        private Uri fileName;
        private Bitmap image;
        private BarcodeDetector detector;
        private ImageView scanedImage;

       @Override
        protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_barcode_tracking);

        scanedImage = (ImageView) findViewById(R.id.ivScanedImage);

        detector = new BarcodeDetector.Builder(getApplicationContext()).build();

        Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        if (intent.resolveActivity(getPackageManager()) != null) {
            startActivityForResult(intent, CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE);
        }

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE && resultCode == RESULT_OK) {
          //  Bundle extras = data.getExtras();
           // image = (Bitmap) extras.get("data");
           // scanedImage.setImageBitmap(image);

            image = BitmapFactory.decodeResource(getApplicationContext().getResources(), R.drawable.ean);
            if (!detector.isOperational()) {
                Log.d("Detector Setup", "could not setup detector");
            } else {
                Frame frame = new Frame.Builder().setBitmap(image).build();
                SparseArray<Barcode> barcodes = detector.detect(frame);
                if(barcodes.size() != 0) {
                    Barcode resultedBarcode = barcodes.valueAt(0);
                    Log.d("Barcode", resultedBarcode.rawValue.toString());
                }

            }
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
    }

    }`   

The code insert for github would not detect alle of my code, thats why it lookes a bit off.. sry about that.. 

**UPDATE**

It's working on a Galaxy s6 Edge, but not on my Nexus 5.. both is running android M (6.0.1)..

**Comment by pchx** [comment]
Does BarcodeDetector.isOperational() report true for the Nexus 5? Do you have an example image that the detector should work on?

See also: https://developers.google.com/vision/multi-tracker-tutorial#querying_the_detector_operational_status

**Comment by zigge** [comment]
Somehow I've fixed it.. I do not know how, but it's working now. Both on my device, nexus 5, and the Gs6 egde.. I think it's a combination of making the pictures a higher res, and a longer distance to the barcode that made the difference.. But if there is a flaw in my code, please do point it out! 

To answer your question, yes the `isOperational()` returns `true`

**Comment by pchx** [comment]
The code looks fine (though it assumes the detector returns at most one barcode, which isn't true).

Glad it's working for you now.
