### ISSUE TITLE
Unable to start Flash/FlashMode.TORCH

### ISSUE THREAD

**Issue by knyttl** [googlesamples/android-vision#72]
Our application depends on the use of flashlight as we scan the codes in low light environment. There seem to be no way of turning it on.

Also this method should be implemented on CameraSource as we need to turn it on/off during scanning.

**Comment by pm0733464** [comment]
There is an open source version of CameraSource which supports setting a flash mode:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java#L574

**Comment by knyttl** [comment]
Would be great if this became part of the official sources.

**Comment by knyttl** [comment]
And what would be a correct way of starting autofocus with this tool as different phones have different autofocus options? The official CameraSource has .setAutoFocus(boolean) which works great.

**Comment by pm0733464** [comment]
The open source API is a bit more broad:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java#L534

You'd call this with Camera.Parameters#FOCUS_MODE_CONTINUOUS_VIDEO for auto focus.

**Comment by TheLester** [comment]
After two years, it's still not part of the official sources...🤦
