### ISSUE TITLE
Flash distorts camera image -> unable to detect barcode

### ISSUE THREAD

**Issue by S0und** [googlesamples/android-vision#73]
This is on the OnePlus One, with Barcode_reader sample project:

[http://imgur.com/gallery/RTwsU/new](http://imgur.com/gallery/RTwsU/new)

**Comment by vbuberen** [comment]
@S0und
Are you serious?
Why you can`t adjust position of your device so flash woudn`t cover the barcode?

**Comment by S0und** [comment]
@vbuberen 
Are you seirous?

http://i.imgur.com/X98dcp0.png

don't you see the difference? that highlight has nothing to do with it, the whole image's aspect ratio is different then the flash is on.

**Comment by vbuberen** [comment]
@S0und 
Oh, sorry. At first glance I thought that you changed aspect ratio during resizing or posting. You see this problem only on OnePlus One or on more devices? Asking, because I hadn`t such problems on Sony Xperia M and Nexus 5 when I tested it in November.

**Comment by pchx** [comment]
The QR code reader is generally not sensitive to aspect ratio (unless you're trying to scan something at an extreme angle), though it is sensitive to lighting. It looks like the flash is washing out part of the code in your first picture.

In any case enabling/disabling flash shouldn't have any effect on the camera's aspect ratio anyway, and if it does, that's a problem with the camera drivers and not the barcode API.
