### ISSUE TITLE
Stop capturing after the first scanned

### ISSUE THREAD

**Issue by Nem2s** [googlesamples/android-vision#74]
Hello! I tried to implement it with onPause() but the application is crashing after 2-3 seconds, and the previewCamera is not stopping.
Is there any workaround to do it?

**Comment by pm0733464** [comment]
How is it crashing?  Can you give a stacktrace?

**Comment by Nem2s** [comment]
I can't reproduce it, sorry. How can i know if the camera had read a barcode? And how can i stop it?

**Comment by Nem2s** [comment]
Ok, so i tried to implement this solution http://stackoverflow.com/questions/32021193/how-to-capture-barcode-values-using-the-new-barcode-api-in-google-play-services?lq=1

then in the_ onFound(String barcodeValue)_i called: _mPreview.stop(); but it only stops the GraphicOverlay object and after a few seconds the screen goes black.
Any ideas about stopping the camera preview?
