### ISSUE TITLE
Random exception while scanning

### ISSUE THREAD

**Issue by knyttl** [googlesamples/android-vision#75]
I am randomly getting this exception which kills completely my application.

```
java.lang.IllegalArgumentException: Null image data supplied.
at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source)
at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
at java.lang.Thread.run(Thread.java:838)
```

Would be great to handle the exception so I could work with it. But as it is in separate thread, I hardly know what to do with it.

**Comment by pm0733464** [comment]
See also [this issue](https://github.com/googlesamples/android-vision/issues/60), which may be what you are seeing.

There was a bug fix to the open source version of CameraSource which I believe fixed this issue.  I suggest trying the open source version in your app:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java
