### ISSUE TITLE
US Driver License scanning issues with PDF417 format

### ISSUE THREAD

**Issue by kkamaraj** [googlesamples/android-vision#77]
I used Mobile Vision API to detect US Driver Licenses. I am able to scan the DL PDF417 barcodes and I see that **_driverLicense_** object is set within _**Barcode**_ object. However for some states (Eg. FL, NC) the **_driverLicense_** object is NULL. 

When I checked the valueFormat in Barcode object it is set to 12 (Barcode.DRIVER_LICENSE) for working scenario and set to 7 (Barcode.TEXT) for non-working scenario. Could you confirm whether this is an issue with BarcodeScanner APIs? Sample code is as follows.

```
BarcodeDetector barcodeDetectorForOutput = new BarcodeDetector.Builder(context)
                .setBarcodeFormats(Barcode.PDF417)
                .build();
        barcodeDetectorForOutput.setProcessor(new Detector.Processor<Barcode>() {
            @Override
            public void release() {
                //NOOP
            }
            @Override
            public void receiveDetections(Detector.Detections<Barcode> detections) {
                SparseArray<Barcode> items = detections.getDetectedItems();
                for (int i=0; i<items.size(); i++) {
                    int key = items.keyAt(i);
                    final Barcode barcode = items.get(key);
                    Logger.d(TAG, "Barcode Format: " + barcode.format);
                    if (!isBarcodeDetected && barcode.format == barcodeType) {
                        Logger.d(TAG, "Barcode Raw: " + barcode.rawValue);
                        Logger.d(TAG, "Barcode valueFormat: " + barcode.valueFormat);
                        break;
                    }
                }
            }
        });
```

**Comment by pchx** [comment]
The DL/ID parser is fairly simple and doesn't work perfectly on IDs from all states, unfortunately. There might be some jurisdiction-specific fields that are tripping it up, or they might not be using a fully spec-compliant encoding.

We'd like to improve it -- if you'd like to help, the anonymized raw text of the non-working cards would be helpful in diagnosing the problem. However, if you aren't comfortable sharing it (or just aren't sure how to completely remove all identifying information) that's okay too!

**Comment by pchx** [comment]
If you can't share the raw values, it would be helpful to know where the first occurrence of "DL" appears in the values that won't parse. Normally, it would be at index 21 (e.g. "@\n \rANSI 636045030002DL").

**Comment by kkamaraj** [comment]
Sure, here is the raw data from the scanner. I used the sample license from internet for FL state.
03-21 14:41:49.422  4238  5774 D BarcodeScannerActivity: Barcode Format: 2048
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: Barcode Raw: @
ANSI 6360100102DL00390201ZF02400052DLDAASAMPLE,IDENTIFICATION,CARD
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DAG2900 APALACHEE PKWY
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DAITALLAHASSEE
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DAJFL
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DAK32399-6552 
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DAQS514403827471
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DARI   
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DAS          
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DAT     
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DBA20110707
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DBB19820707
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DBC2
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DBD20070502
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: DBHN         
ZFZFADUPLICATE: 20070504  5774 D BarcodeScannerActivity: DAU507
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: ZFB 
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: ZFCQ010705040016
03-21 14:41:49.429  4238  5774 D BarcodeScannerActivity: ZFD

**Comment by kkamaraj** [comment]
[Sample FL DL.PDF](https://github.com/googlesamples/android-vision/files/174436/Sample.FL.DL.PDF)
Attached the sample license card.

**Comment by kkamaraj** [comment]
I got the NC state info and removed the personal info. Let me know whether this helps. This is from a valid NC state DL.

@
 AAMVA36004001DL00280208DLDABLASTNAME
DACFIRSTNAME
DADMIDDLE MIDDLE MIDDLE
DAE
DAL123 SAMPLE ST
DAM
DANCHARLOTTE
DAONC
DAP12345-6789
DAQ99999999
DARC
DASNone
DATNone
DAV6-04
DAYBLU
DAZBRO
DBA11-28-2019
DBB04-01-1984
DBCM
DBD06-11-2012
DBHY

**Comment by kkamaraj** [comment]
Here is the NJ  state DL which is working fine, 03-21 17:53:57.419 28002 28431 D BarcodeScannerActivity: Barcode Format: 2048
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: Barcode Raw: @
ANSI 636036040002DL00410318ZN03590153DLDAQK00000000000000          
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DCSLASTNAME
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DDEU
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DACFIRSTNAME
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DDFU
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DAD
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DDGU
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DCAD     
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DCBNONE                
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DCDNONE    
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DBD02222014
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DBB01011900
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DBA03192017
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DBC1
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DAU064 in
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DAYBLK
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DAG107 BERMUDA DR                     
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DAINESHANIC STATI      
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DAJNJ
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DAK088534286  
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DCFED201405300000212        
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DCGUSA
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DDAB
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: DDB07232010
ZNZNAFN7:53:57.420 28002 28431 D BarcodeScannerActivity: DDDT
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: ZNB19.88
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: ZNCRENC
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: ZNETEMP IMMGR STATUS
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: ZNFBLK
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: ZNH88:igJvvXLJs8EWsvn8in7RvzDTmCOYM3CSgdgdgdfFgg/u0SdDaYt2IXGALST10ufQM8WmBSciv60GNuORlAh82cQ==;0291;
03-21 17:53:57.420 28002 28431 D BarcodeScannerActivity: Barcode **Obj:com.google.android.gms.vision.barcode.Barcode$DriverLicense@80230b**

**Comment by pchx** [comment]
Thanks, this is very helpful (though in the future, it would be great to get an escaped literal string that preserves special characters, e.g. "@\n \rANSI [...]\r").

The FL and NC licenses both violate the AAMVA spec in a couple ways, so we're going to make our parser more lenient for future releases.

**Comment by kkamaraj** [comment]
Thanks for the update. Could you confirm the timeline for the release with improved parser?

**Comment by pchx** [comment]
We don't have a timeline to announce, but I expect a new release within a couple of months.

**Comment by jesse-amano** [comment]
Oregon license _sticker_ (the owner moved and received a sticker from the DMV to replace the barcode with new street address information).
There are lots of leading and trailing spaces for some reason and the ANSI/DL code is missing.
```
D/BarcodeScannerActivity: @
                                                                                      DAALAST, FIRST MIDDLE                 
                                                                                      DAG                                    
                                                                                      DAL5555 NUMBERED AVE                    
                                                                                      DAIPORTLAND            
                                                                                      DAJOR
                                                                                      DAK97215      
                                                                                      DARC I 
                                                                                      DASBD        
                                                                                      DAT      
                                                                                      DAU009
                                                                                      DAW135
                                                                                      DBAYYYYMMDD[license expires]
                                                                                      DBBYYYYMMDD[date of birth]
                                                                                      DBC1[num license cards issued]
                                                                                      DBDYYYYMMDD[date license issued]
```

**Comment by pchx** [comment]
Wow. That doesn't even attempt to follow the specs -- unfortunately, our parser won't recognize that text as DL/ID data without the leading "@\n \r(ANSI|AAMVA)". It also doesn't contain the required directory information.

**Comment by jesse-amano** [comment]
It's pretty bad. I'm just going to write a super lenient fallback for the case where despite best efforts the `BarcodeDecoder` can only return `Barcode.TEXT`. Might need to do a switch or something, based on what comes out of the `DAJ` field. I hope Oregon gets its things in order soon, but even if they fixed it tomorrow people would still be carrying around licenses like this through 2021.

**Comment by jesse-amano** [comment]
Actually, please disregard the earlier sample I posted; I'm not sure why, but escaping the string correctly and dumping it on a single line made the prefices and suffices I was expecting show up.

These samples are also from Oregon and don't register as driver's licenses, even though they do have the `@\n \rANSI` prefix. They're malformed in other ways, of course...
(1234567 is a placeholder for their ID number)

`@\nN\rANSI 6360290102DL00390285ZO03240027DLDAQ1234567                 \nDAALAST, FIRST MIDDLE                 \nDAG                                    \nDAL5555 NUMBERED AVE                    \nDAIPORTLAND            \nDAJOR\nDAK97215      \nDARC I \nDASBD        \nDAT      \nDAU009\nDAW135\nDBAYYYYMMDD\nDBBYYYYMMDD\nDBC1\nDBDYYYYMMDD\n\rZOZOAFIRST LICENSED YYYYMMDD\r`

`@\n\rANSI 6360290102DL00390192ZO02310031DLDAQ1234567\nDAASECOND LAST, FIRST M\nDAG\nDAL55555 NAMED DR APT 101\nDAIBEAVERTON\nDAJOR\nDAK97006      \nDARC   \nDASBD        \nDAT      \nDAU509\nDAW135\nDBAYYYYMMDD\nDBBYYYYMMDD\nDBC1\nDBDYYYYMMDD\nZOZOAFIRST LICENSED MM-DD-YYYY\n`

(Yes, the format of the date `ZOZO` field is different between the two.)

**Comment by pchx** [comment]
Thanks for the examples!

However, it appears that the process of redacting personal information may have changed the length of some fields (our updated parser fails on the snippets you provided). The large block of numbers in DL/ID data is a bunch of offsets, which means you must take care not to add/remove any characters when sanitizing it.

**Comment by jesse-amano** [comment]
Ah, my mistake. These should match the original byte positions:

`@\nN\rANSI 6360290102DL00390285ZO03240027DLDAQ1234567 \nDAALASTN, FIRST MIDDLE \nDAG \nDAL5555 NE NNTH AVE \nDAIPORTLAND \nDAJOR\nDAK97215 \nDARC I \nDASBD \nDAT \nDAU009\nDAW135\nDBAYYYYMMDD\nDBBYYYYMMDD\nDBC1\nDBDYYYYMMDD\n\rZOZOAFIRST LICENSED YYYYMMDD\r`

`@\n�\rANSI 6360290102DL00390192ZO02310031DLDAQ1234567\nDAALASTN, FIRST M\nDAG\nDAL55555 NE ANOTHER DR APT 101\nDAIBEAVERTON\nDAJOR\nDAK97006 \nDARC \nDASBD \nDAT \nDAU509\nDAW135\nDBAYYYYMMDD\nDBBYYYYMMDD\nDBC1\nDBDYYYYMMDD\nZOZOAFIRST LICENSED MM-DD-YYYY\n`

**Comment by pchx** [comment]
Unfortunately, both of those examples are badly broken.

The first claims to contain a DL block starting at offset 39 with length 285 ("DL00390285") that overruns the entire string. The second declares a block ("DL00390192") that extends partway into the next ZO block.

**Comment by iamMehedi** [comment]
Doesn't detect barcode in this sample image which contains data for a NY passport. 
![1-back](https://cloud.githubusercontent.com/assets/3691635/18395001/572d346e-76de-11e6-8237-970e8dfa9ff9.jpg)

Tried the barcode reader sample on a Nexus 5.

**Comment by pchx** [comment]
Thanks for the sample. The raw contents ("@ \n\n\nANSI") are unfortunately wildly incompatible with the specification, which says entries begin with "@\n \rANSI".

However, I suspect that many sample drivers licenses are produced manually and are full of errors that don't occur "in the wild". Real New York licenses decode fine with our parser.

**Comment by iamMehedi** [comment]
Thanks for the explanation @pchx

**Comment by pchx** [comment]
The latest version of our Barcode API (part of [Google Play Services 10.0](https://developers.google.com/vision/release-notes#google_play_services_100)) makes the DL/ID parser more lenient; it should handle a wider range of licenses now (there may still be some remaining edge cases, however).

**Comment by kkamaraj** [comment]
Cool @pchx. Let me test it out this week. Thanks for the heads up.

**Comment by infowire** [comment]
Hello @pchx. I was wondering when does length start 2nd DL  and ends where ?
 @

ANSI 6360350201DL00**29**0**180**_DL_DAASAZZLAUZKAS,JUZZAS
DAQS24242043364
DBA20171223
DBB19461213
DAG30 LILWE AVE
DAIPOX LAKE
DAJIL
DAK600600000  
DARD
DASB         
DAT*****
DBD20150115
DBCM
DAU509
DAW120
DAYBRO

**Comment by ZachPierce** [comment]
Not sure if this thread is still alive but Im trying to parse some drivers license at work. The issue Im running into is that the data from the scanner is coming back as one line with no return characters to separate the data fields. Anyone else run into this issue?

**Comment by tway24** [comment]
@emottau I would suggest to refer to AAMVA DL spec (Table D.1 — 2D symbols header format). Also, if you see any issue in parsing please open new issue as this is closed.

**Comment by marksmanaz** [comment]
> Can someone fill me in on the exact format including the /n and /r? Also, what is the diamond character with the questionmark in it? Anyone know?

/n is line feed that separates the individual data objects in the record. /r is carriage return that as far as I can tell helps locate beginning and end to the record. For example in the Arizona DL AAMVA 2D barcode the record is ended with (\n\n\r) this is the only occurrence of this pattern so I can easly know when the record is completely read. The diamond is actual what's called a record separator "rs". When decoding the buffer it has no clue what it is. In javascript I was able to use it to denote the start of the record in an Arizona DL using this code: str.includes("\u001e\r"+"ANSI") record separator, carriage return and "ANSI"  is the beginning of the record.

**Comment by marksmanaz** [comment]
> Not sure if this thread is still alive but Im trying to parse some drivers license at work. The issue Im running into is that the data from the scanner is coming back as one line with no return characters to separate the data fields. Anyone else run into this issue?

My guess it could be your bar code scanner is programmed to trim any spaces and hidden characters as it outputs . Try factory reset on the scanner.

**Comment by naveen21sharma** [comment]
Hi Guys,
I am facing issue while parsing dob from id. I know it comes with DBB but I am getting two different date format for dob like-
04161964 on one card
19820120 on another card, 
Both are from same state so , can you please let me know how can I make a dateFormat by which I can get proper DOB.

**Comment by kkamaraj** [comment]
@naveen21sharma I would try to format with pattern in first case if it fails(most likely a ParseException) then I would try for the next pattern. Unfortunately there is no straight-forward solution in your case.

**Comment by samworldllc** [comment]
@pchx i need some help with NY barcode it has some kind of hash how to decode this hash it looks like made with the fields of id please guide me what should i do...this is the hash in NY id .... : hKL'P3K1i-Fs_o-h$Ah;IcsM;CI6,2+m\m;p@W=j

**Comment by AndroidDeveloperMCT** [comment]
Any update on this parse formatting? Please let me know
