### ISSUE TITLE
No support for Raw Bytes from scan

### ISSUE THREAD

**Issue by djak250** [googlesamples/android-vision#85]
Some barcode implementations include a FNC1 character, specifically CODE_128's. These are necessary to detect in the event that a barcode contains two variable length values encoded to denote the end of one section, and the beginning of the next identifier.

I attempted to get the bytes from the rawData from a barcode, but the FNC1 character byte is missing. I've confirmed that the barcode does indeed contain one with zxing.

**Comment by pchx** [comment]
I've confirmed that our Code128 implementation doesn't handle FNC characters at all. We'll look into returning control codes in the rawValue for future releases.

**Comment by djak250** [comment]
Awesome. Thanks for giving me an update. We use them often in our mobile solution, and I'd love to read it in quickly in-app instead of outsourcing the functionality to zxing using Barcode Scanner.

**Comment by pchx** [comment]
The latest version of our Barcode API (part of [Google Play Services 10.0](https://developers.google.com/vision/release-notes#google_play_services_100)) now returns FNC1 characters in Code128 results.
