### ISSUE TITLE
Not able to resource lib in gradle

### ISSUE THREAD

**Issue by jd-alexander** [googlesamples/android-vision#9]
![screenshot_2015-08-18-12-06-47](https://cloud.githubusercontent.com/assets/1509205/9336806/1fe7a3e6-45a1-11e5-938c-48c451cb2759.png)

**Comment by Crustus** [comment]
I had same problem. U must update Android tools, etc... with SDK Manager. Then it should works. Seems this version is not in Maven yet

**Comment by jd-alexander** [comment]
Thanks I did that and it's fine now.
