### ISSUE TITLE
Mobile Vision is not working on Google Play Services v9

### ISSUE THREAD

**Issue by vietnt134** [googlesamples/android-vision#99]
Hello all, 

Google Play service v9 has released and disable Mobile Vision, can anyone help me how to work around with this?

Many thanks

**Comment by vietnt134** [comment]
It make a huge impact on my app, please can anyone have any advise?

**Comment by pm0733464** [comment]
This issue is tracked [here](https://github.com/googlesamples/android-vision/issues/98).

**Comment by vietnt134** [comment]
Okay thank you hope it will be fixed soon because my customer are not happy....do you have any idea how to deal with this right now? because my app is a scan barcode app without this mobile vision it really suck...suck I mean noone will use my app anymore.

**Comment by felipeleusin** [comment]
I had to resort to solutions like https://github.com/zxing/zxing/wiki/Scanning-Via-Intent so far while MobileVision is unusable.

**Comment by vietnt134** [comment]
Hi felipeleusin,

I have used ZXing before then it has problem with some device (Android 4.4.4 or older), the camera is too slow to detect a barcode...anyway thanks for your answer :santa:

**Comment by felipeleusin** [comment]
Yeah. I know it's not perfect but I think it's the easiest solution so far. Best of luck!

**Comment by sparkym3** [comment]
It has been re-enabled with 9.2. This issue can be closed.
